Sc 3312/amazon s3 remove file s
shipyardapp/amazons3-blueprints pull request #2
Opened 2022-08-19 19:49 UTC by Shamwayne

2022-08-22 18:05 UTC, smjohnsonShipyard commented
![image](https://user-images.githubusercontent.com/104784108/185988839-92f6bd94-fe4b-4bd8-823d-818d5c58a79f.png)
Not sure if this is fixable on your side, but I put a file name that doesn't exist in S3 and it still says that the file can be deleted

2022-08-22 18:16 UTC, smjohnsonShipyard commented
Make sure you update the requirements.txt for both of these as well.

2022-08-23 03:20 UTC, ericelsken requested changes

2022-08-23 03:20 UTC, ericelsken commented on amazons3_blueprints/remove_files.py
> +from ast import literal_eval
This isn't being used and can be removed?

2022-08-23 03:20 UTC, ericelsken commented on amazons3_blueprints/remove_files.py
> +            sys.exit(1)
Do we want an non-succesful exit code if no files are found, @smjohnsonShipyard ?

2022-08-23 03:20 UTC, ericelsken commented on amazons3_blueprints/remove_files.py
> +            print(f'{num_matches} files found. Preparing to upload...')
upload -> remove.

2022-08-23 13:26 UTC, smjohnsonShipyard commented on amazons3_blueprints/remove_files.py
> +            sys.exit(1)
I believe that would make sense. [](edited-with-Axolo)

2022-10-31 20:07 UTC, merged