Sc 3314/amazon s3 move file s
shipyardapp/amazons3-blueprints pull request #3
Opened 2022-08-19 20:11 UTC by Shamwayne

2022-08-22 17:26 UTC, smjohnsonShipyard commented
![image](https://user-images.githubusercontent.com/104784108/185982323-5145e732-17d7-47e3-bdff-b533c789ce7c.png)
Getting this error on run time on my end.

2022-08-23 03:17 UTC, ericelsken requested changes

2022-08-23 03:17 UTC, ericelsken commented on amazons3_blueprints/move_file.py
> +from ast import literal_eval
This isn't being used anywhere - you can remove?

2022-08-23 03:17 UTC, ericelsken commented on amazons3_blueprints/move_file.py
> +    s3_response = s3_connection.list_objects_v2(Bucket=bucket_name, Prefix=source_folder)
Is this guaranteed to return all matches, or is the call paged in some way. If it is paged, we need to update to fetch all pages.

2022-08-24 16:24 UTC, Shamwayne commented on amazons3_blueprints/move_file.py
> +    s3_response = s3_connection.list_objects_v2(Bucket=bucket_name, Prefix=source_folder)
the maximum number of objects listed at a time is 1000 objects, with an option to start listing objects after an offset i.e (start listing from what would have been the 1000th matched object going onwards).

2022-10-31 20:07 UTC, merged