Amazon add move remove
shipyardapp/amazons3-blueprints pull request #4
Opened 2022-10-10 15:30 UTC by wrp801

Combined the following branches into one:
- sc-3312/amazon-s3-remove-file-s 
- sc-3314/amazon-s3-move-file-s

2022-10-24 20:12 UTC, blakeburch commented on amazons3_blueprints/move_file.py
> +            destination_folder_name, destination_file_name
I believe you'll want to use something like `determine_destination_full_path()` from shipyard_utils. Right now, if you leave destination_file_name empty, it just creates a file named `None`. It should inherit the original file name.

2022-10-24 20:18 UTC, blakeburch commented on amazons3_blueprints/move_file.py
> +    s3_response = s3_connection.list_objects_v2(Bucket=bucket_name, Prefix=source_folder)
When I use regex_match this is returning with `AttributeError: 's3.ServiceResource' object has no attribute 'list_objects_v2'`

2022-10-24 20:23 UTC, blakeburch commented on amazons3_blueprints/move_file.py
> +                destination_folder_name, key_name
Same thing in this section. You're going to need the shipyard_utils `determine_destination_full_path` logic because we need to see if there are multiple matches. If so, and a name is specified, it needs to be enumerated. If so, and a name isn't specified, the original name gets used. If not, and a name is specified, it doesn't need enumeration. If not, and a name isn't specified, the original name gets used.

All that logic is taken care of with `determine_destination_full_path()`

2022-10-24 20:29 UTC, blakeburch commented
Remove functionality seems to be good.

Unable to test "move_file.py" in full due to issues with `regex_match`. Left what notes I could.

Biggest thing is testing for all cases of regex/exact match when moving the file(s).

2022-10-24 20:30 UTC, blakeburch requested changes
See comments.

2022-10-27 15:02 UTC, wrp801 commented on amazons3_blueprints/move_file.py
> +                destination_folder_name, key_name
This has been updated

2022-10-27 15:03 UTC, wrp801 commented on amazons3_blueprints/move_file.py
> +    s3_response = s3_connection.list_objects_v2(Bucket=bucket_name, Prefix=source_folder)
This has been fixed

2022-10-27 15:03 UTC, wrp801 commented on amazons3_blueprints/move_file.py
> +            destination_folder_name, destination_file_name
This has been fixed

2022-10-31 15:33 UTC, wrp801 commented
When using the `regex_match` functionality and when supplying the `destination-file-name`, the script needs to rename the matches with the supplied `destination-file-name` and the _1, _2, _3, _n suffixes. It is currently using the original name and appending the suffix

2022-10-31 15:34 UTC, blakeburch commented
<https://github.com/shipyardapp/databricks-blueprints/blob/main/databricks_blueprints/upload_file_to_dbfs.py> Example of the most recent Blueprint using the shipyard_utils functionality for this.

2022-10-31 19:02 UTC, blakeburch approved these changes

2022-10-31 19:02 UTC, blakeburch commented
@wrp801 Good to merge, increment the tag, publish the Blueprints on Shipyard, and update the requirements to use the new tag.

2022-10-31 19:03 UTC, wrp801 commented
Will do!

2022-10-31 19:12 UTC, wrp801 commented
@ericelsken - Can you approve this so I can merge?

2022-10-31 19:29 UTC, ericelsken approved these changes

2022-10-31 19:29 UTC, ericelsken commented
Done.

2022-10-31 20:07 UTC, merged